spring:  application:    name: aws-lambda-connect-rds  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver    url: ${DB_URL}    username: ${USERNAME}    password: ${PASSWORD}      jpa:    generate-ddl: true    show-sql: true    properties:      format-sql: true    hibernate:      ddl-auto: update
aws:
  services:
    auto:
      configuration:
        enabled: false
    s3:
      client:
        enabled: false
    rds:
      client:
        enabled: false    